### ISSUE TITLE
Move all remaining repositories over to github

### ISSUE THREAD

**Issue by gforcada** [plone/buildout.coredev#68]
Looking at sources.cfg from 5.0 branch these are the repositories still hosted on subversion:
- z3c.formwidget.query
- Products.CMFCore
- Products.CMFDefault
- Products.CMFUid
- Products.DCWorkflow
- Products.ExternalEditor

I see that @tdesvenain @do3cc have been moving some packages lately, would it be possible to move those as well?

**Comment by do3cc** [comment]
You missed Products.Genericsetup, it should be on svn too

**Comment by do3cc** [comment]
Everything CMF related has a discussion going on where to move. It won't be github as a canonical repo. At the moment a self hosted gitlab system is favored. GenericSetup is part of CMF

**Comment by gforcada** [comment]
According to sources.cfg Products.GenericSetup is on github: https://github.com/zopefoundation/Products.GenericSetup

**Comment by do3cc** [comment]
That is an error which was fixed by Eric some weeks ago, maybe it resurfaced

**Comment by gforcada** [comment]
I see that on 4.3 P.GenericSetup is indeed still pointing to svn, should be the same on 5.0 right?

**Comment by do3cc** [comment]
yes

**Comment by gforcada** [comment]
Moved back.

**Comment by tisto** [comment]
We still have the option to clone these repositories into the Plone organisation. The canonical versions will still be in svn or whatever, but the CMF developers would be ok with that (I talked to them about it some time ago). We just have to keep them in sync somehow, but since nobody is really working on it anyways that shouldn't be a big problem. Though, we have to check if there is a license problem if we clone those repos. @polyester ?

**Comment by polyester** [comment]
Licensing is on a repo-by-repo basis, there are packages in the Plone org with different licenses already. Moving stuff into Plone org does _not_ constitute a license change by itself. So as long as the original licensing is kept in place, there's no problem. If we want to fork under another license that needs very careful reviewing. But there is no reason not to have some ZPL packages in the Plone organisation, as long as the license files are kept intact.

**Comment by jensens** [comment]
Update, these are todo:
- z3c.formwidget.query 
- Products.ExternalEditor

Both still svn-only.

**Comment by gforcada** [comment]
Would it be ok to move temporarily those repositories to someone's github accounts while the legal stuff is taken care of? There's some jenkins jobs broken due to that and it prevents doing more interesting stuff...

**Comment by mauritsvanrees** [comment]
I have asked on the zope-dev list if someone can move it, or if I myself can move it. Seems like I can create new repos in the zopefoundation github organization.

**Comment by gforcada** [comment]
Great news! :happy:

**Comment by mauritsvanrees** [comment]
The first one is there: https://github.com/zopefoundation/z3c.formwidget.query
I have updated the coredev sources.cfg and added it to the checkouts.
If you already have a subversion checkout, mr.developer will complain and quit and you will need to remove it manually.

Products.ExternalEditor is giving me some problems due to too much copying around of trunk, tags and branches.  Trying another approach now, but this is taking longer.

**Comment by gforcada** [comment]
:beers: yay!!

**Comment by mauritsvanrees** [comment]
Products.ExternalEditor updated as well: https://github.com/zopefoundation/Products.ExternalEditor

Done!
